# Generated by Django 2.1 on 2020-06-22 16:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projeto_avaliado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Peso',
        ),
        migrations.RemoveField(
            model_name='alternativa',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='avaliacaoalternativas',
            name='alternativas',
        ),
        migrations.RemoveField(
            model_name='avaliacaoalternativas',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='avaliacaocriterios',
            name='criterios',
        ),
        migrations.RemoveField(
            model_name='avaliacaocriterios',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='criterio',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='decisor',
            name='avaliou_alternativas',
        ),
        migrations.RemoveField(
            model_name='decisor',
            name='avaliou_criterios',
        ),
        migrations.AddField(
            model_name='alternativa',
            name='imagem',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
        migrations.AddField(
            model_name='avaliacaoalternativas',
            name='avaliacao',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='x'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacaocriterios',
            name='avaliacao',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criterio',
            name='numerico',
            field=models.BooleanField(default=False),
        ),
    ]
