# Generated by Django 2.1 on 2020-06-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projeto_avaliado'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterio',
            name='numerico',
            field=models.BooleanField(default=True),
        ),
    ]
