# Generated by Django 2.1 on 2020-06-22 16:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200622_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoalternativas',
            name='avaliacao',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
        migrations.AlterField(
            model_name='avaliacaocriterios',
            name='avaliacao',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
    ]
